modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="electrical_technologies"
version="1.0.0"
displayName="Electrical Technologies"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Animeshnik, MCreator"

[[dependencies.electrical_technologies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




